### PR TITLE
QR UI

### PR DESCRIPTION
**Pull request by victorsmith**
The only thing left to do is the indented answer forum (Reddit style).
I tried for a couple of hours last night, but nothing was working so I figured I'd move onto the backend code (for question forum). 
Getting the basics of the q&a forum seems more significant for part 3.

### CODE REVIEW

**Comment by debecerra** [comment]
@victorsmith I cloned your branch to look over the changes but I'm not able to run it. I'm not sure if I'm missing something, but it says the symbol R.id.list_experiment is unknown

**Comment by debecerra** [comment]
Are you able to check this out and fix it before we merge?

**Comment by victorsmith** [comment]
@debecerra I can take a look later tonight (~10ish). I only added new content, so I'm not sure what would be causing the problem.

**Comment by debecerra** [comment]
This PR is outdated and is no longer needed

**Pull request closed without merging**
